### ISSUE TITLE
do these come in linux and clap

### ISSUE THREAD

**Issue by RustoMCSpit** [unplugred/vsts#2]
hi! this website says these plugins come in linux and clap https://linuxdaw.org/?d=UnplugRed&f=clap&p=f&l=o

id like to add this here https://github.com/RustoMCSpit/awesome-linux-clap-list but i need the plugins to be added to the releases

**Comment by unplugred** [comment]
Hey. Releases are available at my website, https://vst.unplug.red/

**Comment by RustoMCSpit** [comment]
which plugins listed there and open source?

**Comment by unplugred** [comment]
all plugins on my website are open source and available in this repository, and vice versa.
as of now the only exception is Diet Audio, which is only available in this repository as its not yet finished, but will be posted on the website once its done.

**Comment by RustoMCSpit** [comment]
and do they come in clap? if so i'll add them to my list. i presume the paid ones are not open source however, right?

**Comment by unplugred** [comment]
please do minimal research before flooding me with questions.
you can easily find the answer by opening the link and downloading any of the plugins.

**Comment by RustoMCSpit** [comment]
> please do minimal research before flooding me with questions. you can easily find the answer by opening the link and downloading any of the plugins.

sorry and thanks
