### ISSUE TITLE
gui too small and unadjustable for mpaint

### ISSUE THREAD

**Issue by RustoMCSpit** [unplugred/vsts#4]
- graphics card model: 2070 super
- operating system: linux mint lts
- daw: bitwig studio 5.2.3 .debian
- vst3/clap/au? clap
- detailed steps to reproduce the bug: open the plugin
- a screenshot if applicable
![image](https://github.com/user-attachments/assets/ef1f7d1f-e254-4d9c-8420-3148b2c1a2ac)

**Comment by unplugred** [comment]
i dont see a problem.
gui scale can be changed via right click menu

**Comment by RustoMCSpit** [comment]
> gui scale can be changed via right click menu

not on linux .deb bitwig apparently. resize is greyed out

![image](https://github.com/user-attachments/assets/84499cb1-c7e1-423e-9762-edd70cd0e4f0)

**Comment by unplugred** [comment]
Hey. I am not the developer of airwindows totape.
Please try right clicking on the body of any of my own plugins (and not the bar on top).
![image](https://github.com/user-attachments/assets/3098043d-7d17-4d54-a627-703cbdc0ac15)

**Comment by unplugred** [comment]
Please open github issues for bug reports only, and send any support requests to the email address on my website.

**Comment by RustoMCSpit** [comment]
it's the same thing with any plugin

![image](https://github.com/user-attachments/assets/1379ea76-8453-4e3a-9935-634d46ee8d02)

**Comment by unplugred** [comment]
Right click ON THE PLUGIN.
NOT the title bar

**Comment by RustoMCSpit** [comment]
> Right click ON THE PLUGIN. NOT the title bar

it works, i apologise. thank you and sorry.
